language: python

python:
  - "3.6"

services:
  - xvfb
  - redis-server

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab
  - sudo apt-get install -y r-base
  - export DISPLAY=:99.0

# command to install dependencies
install:
  - pip install -r requirements/requirements-common.txt
  - pip install codecov
  - python setup.py develop

before_script:
  - python manage.py makemigrations notifications_plugin
  - python manage.py makemigrations stats
  - python manage.py makemigrations
  - python manage.py migrate auth
  - python manage.py migrate

# command to run tests and coverage
script:
  - coverage erase
  - celery multi start 1 -A online_test worker -B
  - coverage run -p manage.py test -v 2 yaksh
  - coverage run -p manage.py test -v 2 stats
  - coverage run -p manage.py test -v 2 grades
  - coverage run -p manage.py test -v 2 yaksh.live_server_tests.load_test
  - coverage run -p manage.py test -v 2 api
  - celery multi stop 1
  - find . -type f -name "*.pid" -exec rm -f {} \;

after_success:
  - coverage combine
  - coverage report
  - codecov

dist:
  xenial

addons:
  firefox: "46.0"
