language: python

python:
  - "2.7"

env:
  - DJANGO=1.8.13
  - DJANGO=1.9.5

# command to install dependencies
install:
  - pip install tornado
  - pip install git+https://github.com/FOSSEE/online_test.git#egg=yaksh-0.1
  - pip install -q Django==$DJANGO
  - pip install -q pytz==2016.4
  - pip install -q python-social-auth==0.2.19
  - pip install selenium

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - python manage.py test -v 2 yaksh
  - python manage.py test -v 2 yaksh.live_server_tests
